apiVersion: v1
kind: Secret
metadata:
  name: "internal-thanos-objstore-config"
  namespace: internal-monitoring
type: Opaque
data:
  objstore.yaml: {{ .Values.spec.objstoreConfig | toYaml | indent 4 | b64enc | quote }}
