apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: internal-monitoring
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  source:
    path: ''
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: {{ .Values.spec.prometheus.targetRevision }}
    helm:
      parameters:
        # Grafana
        - name: grafana.sidecar.datasources.url
          value: "http://internal-thanos-stack-query-frontend.internal-monitoring.svc.cluster.local:9090"

        # Grafana Ingress
        - name: grafana.ingress.enabled
          value: "true"
        - name: grafana.ingress.hosts
          value: {{ print "{" .Values.spec.grafana.url "}" | quote }}
        - name: grafana.ingress.annotations.kubernetes\.io/ingress\.class
          value: nginx
        - name: grafana.ingress.annotations.kubernetes\.io/tls-acme
          value: '"true"'
        - name: grafana.ingress.annotations.cert-manager\.io/cluster-issuer
          value: letsencrypt-prod
        - name: grafana.ingress.tls[0].hosts[0]
          value: {{ .Values.spec.grafana.url }}
        - name: grafana.ingress.tls[0].secretName
          value: grafana-tls-secret

        # Alert Manager
        - name: alertmanager.enabled
          value: "false"

        # Prometheus Operator
        - name: prometheusOperator.enabled
          value: "false"

        # Prometheus
        - name: prometheus.enabled
          value: "false"
        
        # Rules
        - name: defaultRules.create
          value: "false"
        
        # Scrapers
        - name: kubeApiServer.enabled
          value: "false"
        - name: kubelet.enabled
          value: "false"
        - name: kubeControllerManager.enabled
          value: "false"
        - name: coreDns.enabled
          value: "false"
        - name: kubeEtcd.enabled
          value: "false"
        - name: kubeScheduler.enabled
          value: "false"
        - name: kubeProxy.enabled
          value: "false"
        - name: kubeStateMetrics.enabled
          value: "false"
        - name: nodeExporter.enabled
          value: "false"
    chart: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - Replace=true
