spec:
  destination:
    project: <project_name>
    server: https://kubernetes.default.svc
  retention:
    type: s3
    config:
      bucket: <s3-bucket>
      endpoint: <s3-region>
      access_key: <s3-access-key>
      secret_key: <s3-secret-key>
  prometheus:
    targetRevision: 8.3.5
